export type CalculatorId = 'roas' | 'cpc' | 'ctr' | 'cpm';

type CalculatorInput = {
  id: string;
  label: string;
  placeholder: string;
  help: string;
};

type CalculatorOutput = {
  id: string;
  label: string;
};

type CalculatorFaq = {
  question: string;
  answer: string;
};

export type CalculatorConfig = {
  id: CalculatorId;
  path: string;
  name: string;
  shortName: string;
  title: string;
  description: string;
  h1: string;
  intro: string;
  inputs: CalculatorInput[];
  outputs: CalculatorOutput[];
  formulas: string[];
  formulaNote?: string;
  example: string;
  faq: CalculatorFaq[];
  related: CalculatorId[];
  cardText: string;
};

export const calculators: Record<CalculatorId, CalculatorConfig> = {
  roas: {
    id: 'roas',
    path: '/roas-calculator/',
    name: 'ROAS Calculator',
    shortName: 'ROAS',
    title: 'ROAS Calculator - Calculate Return on Ad Spend',
    description: 'Free ROAS calculator to calculate return on ad spend from revenue and ad spend. Includes formula, example, break-even ROAS, and related PPC calculators.',
    h1: 'ROAS Calculator',
    intro: 'Calculate return on ad spend from revenue and ad spend. Add profit margin to estimate break-even ROAS and see whether the result is above or below break-even.',
    inputs: [
      { id: 'revenue', label: 'Revenue', placeholder: '$10,000', help: 'Total revenue attributed to your ads.' },
      { id: 'adSpend', label: 'Ad Spend', placeholder: '$2,500', help: 'Total amount spent on the ads.' },
      { id: 'profitMargin', label: 'Profit Margin % (optional)', placeholder: '25%', help: 'Optional profit margin. You can enter 25, 25%, or 0.25.' }
    ],
    outputs: [
      { id: 'roasRatio', label: 'ROAS Ratio' },
      { id: 'roasPercentage', label: 'ROAS Percentage' },
      { id: 'breakEvenRoas', label: 'Break-even ROAS' },
      { id: 'profitabilityStatus', label: 'Profitability Status' }
    ],
    formulas: ['ROAS = Revenue / Ad Spend', 'Break-even ROAS = 1 / Profit Margin'],
    formulaNote: 'For break-even ROAS, use profit margin as a decimal. For example, 25% profit margin is 0.25.',
    example: 'If revenue is $10,000 and ad spend is $2,500, ROAS is 4.0x or 400%.',
    faq: [
      { question: 'What is ROAS?', answer: 'ROAS means return on ad spend. It compares revenue generated by advertising with the amount spent on those ads.' },
      { question: 'How do you calculate ROAS?', answer: 'To calculate ROAS, divide revenue by ad spend. For example, $10,000 in revenue divided by $2,500 in ad spend equals 4.0x ROAS.' },
      { question: 'What is a good ROAS?', answer: 'A good ROAS depends on your margins, business model, channel, and growth goals. Start by comparing your ROAS with your break-even ROAS.' },
      { question: 'What is break-even ROAS?', answer: 'Break-even ROAS is the minimum ROAS needed to cover ad spend based on profit margin. With a 25% margin, break-even ROAS is 4.0x.' },
      { question: 'What is the difference between ROAS and ROI?', answer: 'ROAS focuses on revenue compared with ad spend. ROI usually considers profit and broader costs beyond the advertising spend itself.' }
    ],
    related: ['cpc', 'ctr', 'cpm'],
    cardText: 'Calculate return on ad spend from revenue and ad spend.'
  },
  cpc: {
    id: 'cpc',
    path: '/cpc-calculator/',
    name: 'CPC Calculator',
    shortName: 'CPC',
    title: 'CPC Calculator - Calculate Cost Per Click',
    description: 'Free CPC calculator to calculate cost per click from ad spend and clicks. Includes formula, example, and related PPC calculators.',
    h1: 'CPC Calculator',
    intro: 'Calculate cost per click from ad spend and clicks. Use the result to compare paid search, paid social, and display campaigns.',
    inputs: [
      { id: 'adSpend', label: 'Ad Spend', placeholder: '$500', help: 'Total amount spent on the ads.' },
      { id: 'clicks', label: 'Clicks', placeholder: '1,000', help: 'Total number of ad clicks.' }
    ],
    outputs: [{ id: 'cpc', label: 'CPC' }],
    formulas: ['CPC = Ad Spend / Clicks'],
    example: 'If ad spend is $500 and you received 1,000 clicks, CPC is $0.50.',
    faq: [
      { question: 'What is CPC?', answer: 'CPC means cost per click. It shows how much you pay on average for each ad click.' },
      { question: 'How do you calculate CPC?', answer: 'To calculate CPC, divide total ad spend by total clicks.' },
      { question: 'What is a good CPC?', answer: 'A good CPC depends on the ad platform, competition, conversion rate, average order value, and target profitability.' },
      { question: 'How can I lower CPC?', answer: 'You can often lower CPC by improving ad relevance, testing better creative, refining targeting, improving quality signals, and removing weak placements or keywords.' },
      { question: 'What is the difference between CPC and CPM?', answer: 'CPC measures cost per click. CPM measures cost per thousand impressions.' }
    ],
    related: ['roas', 'ctr', 'cpm'],
    cardText: 'Calculate average cost per click from spend and clicks.'
  },
  ctr: {
    id: 'ctr',
    path: '/ctr-calculator/',
    name: 'CTR Calculator',
    shortName: 'CTR',
    title: 'CTR Calculator - Calculate Click-Through Rate',
    description: 'Free CTR calculator to calculate click-through rate from clicks and impressions. Includes formula, example, and related PPC calculators.',
    h1: 'CTR Calculator',
    intro: 'Calculate click-through rate from clicks and impressions. Use CTR to understand how often impressions turn into clicks.',
    inputs: [
      { id: 'clicks', label: 'Clicks', placeholder: '500', help: 'Total number of ad clicks.' },
      { id: 'impressions', label: 'Impressions', placeholder: '25,000', help: 'Total number of ad impressions.' }
    ],
    outputs: [{ id: 'ctr', label: 'CTR' }],
    formulas: ['CTR = Clicks / Impressions × 100'],
    example: 'If you got 500 clicks from 25,000 impressions, CTR is 2%.',
    faq: [
      { question: 'What is CTR?', answer: 'CTR means click-through rate. It shows the percentage of impressions that resulted in clicks.' },
      { question: 'How do you calculate CTR?', answer: 'To calculate CTR, divide clicks by impressions and multiply by 100.' },
      { question: 'What is a good CTR?', answer: 'A good CTR depends on the channel, campaign type, audience, ad format, and search intent.' },
      { question: 'Why is CTR important?', answer: 'CTR helps you understand whether people are responding to your ad after seeing it.' },
      { question: 'What is the difference between CTR and conversion rate?', answer: 'CTR measures clicks divided by impressions. Conversion rate measures conversions divided by clicks or sessions.' }
    ],
    related: ['roas', 'cpc', 'cpm'],
    cardText: 'Calculate click-through rate from clicks and impressions.'
  },
  cpm: {
    id: 'cpm',
    path: '/cpm-calculator/',
    name: 'CPM Calculator',
    shortName: 'CPM',
    title: 'CPM Calculator - Calculate Cost Per Thousand Impressions',
    description: 'Free CPM calculator to calculate cost per thousand impressions from ad spend and impressions. Includes formula, example, and related PPC calculators.',
    h1: 'CPM Calculator',
    intro: 'Calculate cost per thousand impressions from ad spend and impressions. Use CPM to compare the cost of reach across ad campaigns.',
    inputs: [
      { id: 'adSpend', label: 'Ad Spend', placeholder: '$1,000', help: 'Total amount spent on the ads.' },
      { id: 'impressions', label: 'Impressions', placeholder: '200,000', help: 'Total number of ad impressions.' }
    ],
    outputs: [{ id: 'cpm', label: 'CPM' }],
    formulas: ['CPM = Ad Spend / Impressions × 1000'],
    example: 'If ad spend is $1,000 and impressions are 200,000, CPM is $5.00.',
    faq: [
      { question: 'What is CPM?', answer: 'CPM means cost per thousand impressions. It shows how much you pay for 1,000 ad impressions.' },
      { question: 'How do you calculate CPM?', answer: 'To calculate CPM, divide ad spend by impressions and multiply by 1,000.' },
      { question: 'What is a good CPM?', answer: 'A good CPM depends on the channel, audience, placement, creative quality, and campaign objective.' },
      { question: 'When should I use CPM?', answer: 'CPM is useful when you compare the cost of reach, awareness, or impression-based campaigns.' },
      { question: 'What is the difference between CPM and CPC?', answer: 'CPM measures cost per thousand impressions. CPC measures cost per click.' }
    ],
    related: ['roas', 'cpc', 'ctr'],
    cardText: 'Calculate cost per thousand impressions from spend and impressions.'
  }
};

export const calculatorList = [calculators.roas, calculators.cpc, calculators.ctr, calculators.cpm];
